version: "3"

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PAYLOAD_URL=http://payload:3001
      - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    depends_on:
      - payload
    restart: unless-stopped
    volumes:
      - ./public:/app/public

  payload:
    build:
      context: ./payload
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/payload
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - PAYLOAD_PUBLIC_SERVER_URL=http://localhost:3001
    depends_on:
      - mongo
    volumes:
      - payload-uploads:/app/uploads
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

# Uncomment if you want to run a local Supabase for development
#  supabase-db:
#    image: supabase/postgres:15.1.0.25
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#    volumes:
#      - supabase-data:/var/lib/postgresql/data
#    restart: unless-stopped

volumes:
  mongo-data:
  payload-uploads:
#  supabase-data:
